### PR TITLE
Conda

### PR DESCRIPTION
**Pull request by doutriaux1**
@xylar first cut. Let me know what you think

### CODE REVIEW

**Comment by xylar** [comment]
@doutriaux1, thanks so much! I was working on essentially the same thing myself but now I see how to handle the dependencies (only in the conda recipe).

So if I understand right, `./setup.py install` would then fail if you tried to run it in an environment where the right dependencies hadn't already been installed.  Clearly not a problem as long as we don't care about supporting pypi.

**Comment by doutriaux1** [comment]
@xylar yes conda essentially separate what's required for building the package from what's required for runnning it.
Once your PR is merged in the main repo I can work on getting this into the conda-forge channel.

**Comment by doutriaux1** [comment]
@xylar I'm working on the a-prime part now, at some point we will need to make a-prime a dependency of this i guess. Is that correct?

**Comment by doutriaux1** [comment]
ooops looks like MPAS-Analysys is under a-prime, not the other way around. My bad.

**Comment by xylar** [comment]
Correct.  This is why a-prime can have the stricter requirements and MPAS-Analysis the looser.  I rebased these changes and made the version numbers not as strict.  I'll force-push as soon as I have done some testing.

**Pull request merged**
